---
title: "HW4"
output: html_document
date: "2022-10-27"
---

```{r loading packages}
#install.packages("countrycode")
library(here)
library(sf)
library(tidyverse)
library(countrycode)
library(janitor)
library(tmap)
library(tmaptools)
```
```{r loading data}
#spatial data
world <- st_read(here("Data/World_Countries_(Generalized)","World_Countries__Generalized_.shp"))
gender <- read.csv(here("Data/HDR21-22_Composite_indices_complete_time_series.csv"),na="NULL")

```
```{r calculating the gender inequality and convert the country name into iso3 in world shp}
gii_index <- gender %>%
  clean_names() %>%
  dplyr::select("iso3","country","gii_2010","gii_2019") %>%
  mutate(gii_diff = gii_2019 - gii_2010)


#world<-clean_names(world)
world_iso3 <- world %>%
  clean_names() %>%
  mutate(iso3 = countrycode(country,origin = "country.name", destination = "iso3c"))
```

```{r join the diff_hdi with spatial data}
world_gii_diff <- world_iso3 %>%
  clean_names() %>%
  merge(., gii_index, by=c("iso3" = "iso3"))

world_gii_diff_2 <- world_iso3 %>%
  clean_names() %>%
  left_join(., gii_index, by=c("iso3" = "iso3"))

tmap_mode("plot")
qtm(world_gii_diff,fill="gii_diff")

```


